### ISSUE TITLE
securitycontext

### ISSUE THREAD

**Issue by samaiyayashraj** [pivotal-cf/docs-mysql-k8s#62]
Hello, 
I'm trying to create a Mysql HA instance from Tanzusql with Mysql operator. 
Is it possible to create an instance with security context configuration?
Ex. I want to pass the below configuration in the Mysql instance.

```
securityContext:
     allowPrivilegeEscalation: false #drop privilage escalation
     privileged: false #run as non-privilaged container
```

**Comment by lenapivotal** [comment]
@samaiyayashraj I'm asking the engineers the question. Will get back to you.

**Comment by lenapivotal** [comment]
@samaiyayashraj response from our devs:
We don't allow users to pass in security context configuration to the MySQL instance.
The operator creates the pod with these values:
```
securityContext:
    fsGroup: 1001
    runAsGroup: 1001
    runAsUser: 1001
    supplementalGroups:
    - 1001
```
Since `securityContext.allowPrivilegeEscalation` and `securityContext.privileged` default to false in Kubernetes (see [docs](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1)), the default outcome matches what you are asking for.

**Comment by samaiyayashraj** [comment]
@lenapivotal , Thanks for the reply.

So using the TanzuSql with Mysql operator only parameters in the below-mentioned template can be configured & noting else can be configured? Is that correct?


```
---
apiVersion: with.sql.tanzu.vmware.com/v1
kind: MySQL
metadata:
  name: mysql
spec:
  storageSize: 1Gi
  imagePullSecret: tanzu-mysql-image-registry

#### Set the storage class name to change storage class of the PVC associated with this resource
  storageClassName: default

#### Set the type of Service used to provide access to the MySQL database.
  serviceType: LoadBalancer

#### Set the name of the Secret used for TLS
  #tls:
    #secret:
      #name: mysql-tls

#### Enable highly available cluster
  highAvailability:
    enabled: true

#### Examples to set resource limit/request for mysql/backup containers.
  resources:

#### This is the container running the mysql server.
   mysql:
     limits:
       cpu: '1.0'
       memory: 800Mi
     requests:
       cpu: '0.75'
       memory: 500Mi

#### This is the sidecar container that manages backups and innodb cluster operations
#    mysqlSidecar:
#      limits:
#        cpu: '0.25'
#        memory: 75Mi
#      requests:
#        cpu: 100m
#        memory: 50Mi
```
